version: '3'
services:
  jenkins:
    build: . # This will use the Dockerfile in the current directory
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - net
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net

networks:
  net:

volumes:
  jenkins_data:
